import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { guidelinesDir } from "../../lib/resources";
import { architectureById } from "../architectures";
import { authById } from "../auth";
import { testLayoutById } from "../test-layout";
import type { Detection } from "../detect";
import type { Selection } from "../selection";
import type { GuidelinesTarget } from "../agents/agent";

const BEGIN = "<!-- nest-boost:begin -->";
const END = "<!-- nest-boost:end -->";

const PREAMBLE = `# NestJS Guidelines (nest-boost)

These guidelines are generated by \`nest-boost\` from the packages detected in this
project. They are regenerated by \`nest-boost update\` — edit your own guidance
outside the nest-boost markers.

**Use the \`nest-boost\` MCP tools** (\`application_info\`, \`list_routes\`,
\`module_graph\`, \`nest_cli\`) to inspect the real application before generating
or moving code — do not guess the module/route structure.
`;

/** Read a guideline file from the packaged resources, or return null if absent. */
function readGuideline(relPath: string): string | null {
  const path = join(guidelinesDir(), relPath);
  return existsSync(path) ? readFileSync(path, "utf8").trim() : null;
}

/**
 * Compose the full guidelines markdown for a project: the preamble, core
 * conventions, any version-specific NestJS notes, and one section per detected
 * ecosystem package that ships a guideline.
 */
export function composeGuidelines(detection: Detection, selection: Selection = {}): string {
  const sections: string[] = [PREAMBLE];

  const version = detection.nest?.major;
  if (version) {
    const versioned = readGuideline(join("nestjs", `${version}.md`));
    if (versioned) sections.push(versioned);
  }

  if (detection.monorepo) {
    const file = detection.workspaceEngine === "nestkit" ? "monorepo-nestkit.md" : "monorepo.md";
    const monorepo = readGuideline(file);
    if (monorepo) sections.push(monorepo);
  }

  const arch = selection.architecture ? architectureById(selection.architecture) : undefined;
  if (arch) {
    const body = readGuideline(arch.guideline);
    if (body) sections.push(body);
  }

  const auth = selection.auth ? authById(selection.auth) : undefined;
  if (auth?.guideline) {
    const body = readGuideline(auth.guideline);
    if (body) sections.push(body);
  }

  const layout = selection.testLayout ? testLayoutById(selection.testLayout) : undefined;
  if (layout) {
    const body = readGuideline(layout.guideline);
    if (body) sections.push(body);
  }

  for (const entry of detection.entries) {
    if (!entry.guideline) continue;
    const body = readGuideline(entry.guideline);
    if (body) sections.push(body);
  }

  return sections.join("\n\n---\n\n") + "\n";
}

/** Write composed guidelines into an agent's target file. */
export function writeGuidelines(
  projectRoot: string,
  target: GuidelinesTarget,
  content: string,
): string {
  const path = join(projectRoot, target.file);
  mkdirSync(dirname(path), { recursive: true });

  if (target.mode === "whole") {
    writeFileSync(path, (target.header ?? "") + content);
    return target.file;
  }

  const block = `${BEGIN}\n${content}${END}\n`;
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (existing.includes(BEGIN) && existing.includes(END)) {
      const replaced = existing.replace(
        new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n?`),
        block,
      );
      writeFileSync(path, replaced);
    } else {
      writeFileSync(path, existing.trimEnd() + "\n\n" + block);
    }
  } else {
    writeFileSync(path, block);
  }
  return target.file;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
